export enum ResourceEnum {
  ALL = "all",
  USER = "user",
  ROLE = "role",
  PERMISSION = "permission",
  DASHBOARD = "dashboard",
  ANNOUNCEMENT = "announcement",
  ACADEMIC = "academic",
  ATTENDANCE = "attendance",
  EXAMINATION = "examination",
  ASSIGNMENT = "assignment",
  FEE = "fee",
  HR = "hr",
  LIBRARY = "library",
  TRANSPORT = "transport",
  TEACHER = "teacher",
  STUDENT = "student",
  REPORT = "report",
  SETTING = "setting",
}
