export enum ResourceEnum {
  ALL = "all",
  USER = "user",
  ROLE = "role",
  PERMISSION = "permission",
  DASHBOARD = "dashboard",
  ANNOUNCEMENT = "announcement",
  ACADEMIC = "academic",
  CLASS = "class",
  PROGRAM = "program",
  ACADEMIC_YEAR = "academic_year",
  TIMETABLE = "timetable",
  ATTENDANCE = "attendance",
  STUDENT_ATTENDANCE = "student_attendance",
  TEACHER_ATTENDANCE = "teacher_attendance",
  LEAVE_REQUEST = "leave_request",
  EXAMINATION = "examination",
  ASSIGNMENT = "assignment",
  FEE = "fee",
  HR = "hr",
  LIBRARY = "library",
  TRANSPORT = "transport",
  TEACHER = "teacher",
  STUDENT = "student",
  REPORT = "report",
  SETTING = "setting",
}

