export const API_ROUTE = {
  AUTH: {
    LOGIN: '/api/v1/auth/login',
    LOGOUT: '/api/v1/auth/logout',
    REFRESH_TOKEN: '/api/v1/auth/refresh-token',
    PROFILE: '/api/v1/auth/profile',
  },
  USER: {
    LIST: '/api/v1/admin/users',
    CREATE: '/api/v1/admin/users',
    GET: '/api/v1/admin/users/:id',
    UPDATE: '/api/v1/admin/users/:id',
    DELETE: '/api/v1/admin/users/:id',
  },
  ROLE: {
    LIST: '/api/v1/admin/roles',
    CREATE: '/api/v1/admin/roles',
    GET: '/api/v1/admin/roles/:id',
    UPDATE: '/api/v1/admin/roles/:id',
    DELETE: '/api/v1/admin/roles/:id',
  },
  PERMISSION: {
    LIST: '/api/v1/admin/permissions',
  },
  STUDENT: {
    LIST: '/api/v1/admin/students',
    CREATE: '/api/v1/admin/students',
    GET: '/api/v1/admin/students/:id',
    UPDATE: '/api/v1/admin/students/:id',
    DELETE: '/api/v1/admin/students/:id',
    SUMMARY: '/api/v1/admin/students/:id/summary',
    ASSIGN_CLASSES: '/api/v1/admin/students/:id/classes',
    PROMOTE: '/api/v1/admin/students/:id/promote',
    BATCH_PROMOTE: '/api/v1/admin/students/batch-promote',
    PAYMENTS: '/api/v1/admin/students/:id/payments',
    RECORD_PAYMENT: '/api/v1/admin/students/:id/payments',
  },
  CLASS: {
    LIST: '/api/v1/admin/classes',
    CREATE: '/api/v1/admin/classes',
    ACADEMIC_YEARS_SUMMARY: '/api/v1/admin/classes/academic-years/summary',
    GET: '/api/v1/admin/classes/:id',
    UPDATE: '/api/v1/admin/classes/:id',
    DELETE: '/api/v1/admin/classes/:id',
    STUDENTS: '/api/v1/admin/classes/:id/students',
    TIMETABLE: '/api/v1/admin/classes/:id/timetable',
    CREATE_TIMETABLE: '/api/v1/admin/classes/:id/timetable',
    UPDATE_TIMETABLE: '/api/v1/admin/classes/timetable/:slotId',
    DELETE_TIMETABLE: '/api/v1/admin/classes/timetable/:slotId',
  },
  PROGRAM: {
    LIST: '/api/v1/admin/programs',
    CREATE: '/api/v1/admin/programs',
    GET: '/api/v1/admin/programs/:id',
    UPDATE: '/api/v1/admin/programs/:id',
    DELETE: '/api/v1/admin/programs/:id',
  },
  TEACHER: {
    LIST: '/api/v1/admin/teachers',
    CREATE: '/api/v1/admin/teachers',
    GET: '/api/v1/admin/teachers/:id',
    UPDATE: '/api/v1/admin/teachers/:id',
    DELETE: '/api/v1/admin/teachers/:id',
    CLASSES: '/api/v1/admin/teachers/:id/classes',
  },
  ATTENDANCE: {
    STUDENTS: '/api/v1/admin/attendance/students',
    STUDENTS_BATCH: '/api/v1/admin/attendance/students/batch',
    STUDENT_SHEET_MATRIX: '/api/v1/admin/attendance/students/matrix',
    STUDENT_SUMMARY: '/api/v1/admin/attendance/students/summary',
    TEACHERS: '/api/v1/admin/attendance/teachers',
    TEACHERS_BATCH: '/api/v1/admin/attendance/teachers/batch',
    TEACHER_SUMMARY: '/api/v1/admin/attendance/teachers/summary',
    LEAVE_REQUESTS: '/api/v1/admin/attendance/leave-requests',
    LEAVE_REQUEST_CREATE: '/api/v1/admin/attendance/leave-requests',
    LEAVE_REQUEST_GET: '/api/v1/admin/attendance/leave-requests/:id',
    LEAVE_REQUEST_UPDATE: '/api/v1/admin/attendance/leave-requests/:id',
    LEAVE_REQUEST_DELETE: '/api/v1/admin/attendance/leave-requests/:id',
    LEAVE_REQUEST_REVIEW: '/api/v1/admin/attendance/leave-requests/:id/review',
  },
  EXAMINATION: {
    RULES_LIST: '/api/v1/admin/examinations/rules',
    RULES_CREATE: '/api/v1/admin/examinations/rules',
    RULES_GET: '/api/v1/admin/examinations/rules/:id',
    RULES_UPDATE: '/api/v1/admin/examinations/rules/:id',
    RULES_DELETE: '/api/v1/admin/examinations/rules/:id',
    RULES_DEFAULT: '/api/v1/admin/examinations/rules/default',
    MATRIX: '/api/v1/admin/examinations/matrix',
    GRADEBOOK_SAVE: '/api/v1/admin/examinations/matrix/save',
    REPORT_CARD: '/api/v1/admin/examinations/report-card/:studentId',
    EXPORT_CSV: '/api/v1/admin/examinations/matrix/export',
  },
  FEE: {
    STRUCTURES_LIST: '/api/v1/admin/fees/structures',
    STRUCTURES_CREATE: '/api/v1/admin/fees/structures',
    STRUCTURES_GET: '/api/v1/admin/fees/structures/:id',
    STRUCTURES_UPDATE: '/api/v1/admin/fees/structures/:id',
    STRUCTURES_DELETE: '/api/v1/admin/fees/structures/:id',
    INVOICES_LIST: '/api/v1/admin/fees/invoices',
    INVOICES_CREATE: '/api/v1/admin/fees/invoices',
    INVOICES_BATCH_GENERATE: '/api/v1/admin/fees/invoices/batch-generate',
    INVOICES_GET: '/api/v1/admin/fees/invoices/:id',
    INVOICES_UPDATE: '/api/v1/admin/fees/invoices/:id',
    INVOICES_RECORD_PAYMENT: '/api/v1/admin/fees/invoices/:id/pay',
    INVOICES_REFUND: '/api/v1/admin/fees/invoices/:id/refund',
    INVOICES_REMINDER: '/api/v1/admin/fees/invoices/:id/reminder',
    EXPENSES_LIST: '/api/v1/admin/fees/expenses',
    EXPENSES_CREATE: '/api/v1/admin/fees/expenses',
    EXPENSES_GET: '/api/v1/admin/fees/expenses/:id',
    EXPENSES_UPDATE: '/api/v1/admin/fees/expenses/:id',
    EXPENSES_DELETE: '/api/v1/admin/fees/expenses/:id',
    EXPENSES_APPROVE: '/api/v1/admin/fees/expenses/:id/approve',
    SUMMARY: '/api/v1/admin/fees/summary',
  },
};

