export const API_ROUTE = {
  AUTH: {
    LOGIN: '/api/v1/auth/login',
    LOGOUT: '/api/v1/auth/logout',
    REFRESH_TOKEN: '/api/v1/auth/refresh-token',
    PROFILE: '/api/v1/auth/profile',
  },
  USER: {
    LIST: '/api/v1/admin/users',
    CREATE: '/api/v1/admin/users',
    GET: '/api/v1/admin/users/:id',
    UPDATE: '/api/v1/admin/users/:id',
    DELETE: '/api/v1/admin/users/:id',
  },
  ROLE: {
    LIST: '/api/v1/admin/roles',
    CREATE: '/api/v1/admin/roles',
    GET: '/api/v1/admin/roles/:id',
    UPDATE: '/api/v1/admin/roles/:id',
    DELETE: '/api/v1/admin/roles/:id',
  },
  PERMISSION: {
    LIST: '/api/v1/admin/permissions',
  },
  STUDENT: {
    LIST: '/api/v1/admin/students',
    CREATE: '/api/v1/admin/students',
    GET: '/api/v1/admin/students/:id',
    UPDATE: '/api/v1/admin/students/:id',
    DELETE: '/api/v1/admin/students/:id',
    SUMMARY: '/api/v1/admin/students/:id/summary',
    ASSIGN_CLASSES: '/api/v1/admin/students/:id/classes',
    PROMOTE: '/api/v1/admin/students/:id/promote',
    BATCH_PROMOTE: '/api/v1/admin/students/batch-promote',
    PAYMENTS: '/api/v1/admin/students/:id/payments',
    RECORD_PAYMENT: '/api/v1/admin/students/:id/payments',
  },
  CLASS: {
    LIST: '/api/v1/admin/classes',
    CREATE: '/api/v1/admin/classes',
    ACADEMIC_YEARS_SUMMARY: '/api/v1/admin/classes/academic-years/summary',
    GET: '/api/v1/admin/classes/:id',
    UPDATE: '/api/v1/admin/classes/:id',
    DELETE: '/api/v1/admin/classes/:id',
    STUDENTS: '/api/v1/admin/classes/:id/students',
    TIMETABLE: '/api/v1/admin/classes/:id/timetable',
    CREATE_TIMETABLE: '/api/v1/admin/classes/:id/timetable',
    UPDATE_TIMETABLE: '/api/v1/admin/classes/timetable/:slotId',
    DELETE_TIMETABLE: '/api/v1/admin/classes/timetable/:slotId',
  },
  PROGRAM: {
    LIST: '/api/v1/admin/programs',
    CREATE: '/api/v1/admin/programs',
    GET: '/api/v1/admin/programs/:id',
    UPDATE: '/api/v1/admin/programs/:id',
    DELETE: '/api/v1/admin/programs/:id',
  },
};

